# role name (same as in oidc backend config)
terraform-vault:
  boundClaims:
    # map of claim values that can take on this role
    emails:
      - 69bnguyen@gmail.com

terraform-grafana:
  boundClaims:
    emails:
      - 69bnguyen@gmail.com

admin:
  boundClaims:
    emails:
      - 69bnguyen@gmail.com
