metadata:
  name: dynamic-role
spec:
  # role type; can be "static" or "dynamic"
  type: dynamic
  # the default number of seconds that this role is valid for
  defaultTtlSeconds: 300 # 5 minutes
  # the maximum number of seconds that this role is valid for
  maxTtlSeconds: 3600 # 1 hour
  # list of creation statements in JSON format
  creationStatements:
    - |
      {
        "db": "example",
        "roles": [
          {
            "role": "read",
            "db": "example"
          }
        ]
      }
