metadata:
  name: example
  # path to the kv secret (excluding the mount path)
  path: example
spec:
  # this indicates kv v2
  enableVersioning: true
  # indicates that the secret already exists in vault; no need to define anything else here
  import: true
