metadata:
  name: example
  # path to the kvv2 secret (excluding the mount path)
  path: example
spec:
  # whether or not to enable versioning (use kvv2 engine)
  enableVersioning: true
  # max number of versions PER KEY; not sure how it works so don't use it
  maxVersions: 2
  # duration in seconds to keep the LATEST version; overrides the secret backend config (only available when enableVersioning is true)
  deleteVersionAfterSeconds: 120

  # key-value map of public (fixed) keys and values (e.g. username, IDs, etc.)
  public:
    username: admin
  # list of secret keys whose values need to be generated and passed in to vault
  generated:
    - password
  # whether this secret should be imported from an existing secret in vault
  import: false
  # interval in which the secret needs to be rotated (regenerated); omit if it shouldn't be rotated automatically
  rotateInterval: 4380h
