metadata:
  name: oidc-google
  description: "Google OIDC backend"
spec:
  # path to oidc secrets in vault
  secretPath: oidc/google
  # mount path for the auth backend
  mountPath: oidc-google
  type: oidc
  oidc:
    discoveryUrl: "https://accounts.google.com"
    redirectUrls:
      - "http://localhost:8250/oidc/callback"
    roleMappings:
      - roleName: terraform-vault
        tokenPolicies:
          - default
          - terraform-vault
        scopes:
          - openid
          - email
        userClaim: "email"
        boundClaims:
          email: "69bnguyen@gmail.com"
        tokenTtlSeconds: 300 # 5 min
      - roleName: terraform-grafana
        tokenPolicies:
          - default
          - terraform-grafana
        scopes:
          - openid
          - email
        userClaim: "email"
        boundClaims:
          email: "69bnguyen@gmail.com"
        tokenTtlSeconds: 14400 # 4 hours
