metadata:
  name: google
spec:
  # path to oidc secrets in vault
  secretPath: oidc/google
  # mount path for the auth backend
  mountPath: oidc-google
  type: oidc
  oidc:
    discoveryUrl: "https://accounts.google.com"
    redirectUrls:
      - "http://localhost:8250/oidc/callback"
      - "http://localhost:54288/ui/vault/auth/oidc/oidc/callback"
    roleMappings:
      - roleName: terraform-vault
        tokenPolicies:
          - default
          - terraform-vault
        scopes:
          - openid
          - email
        userClaims: "email"
        boundClaims:
          email: "69bnguyen@gmail.com"
        tokenTtlSeconds: 300 # 5 min
