metadata:
  name: argocd
  path: argocd
  timestamp: '2025-05-11T03:50:42+00:00'
spec:
  enableVersioning: true
  generated:
  - password
  import: false
  public:
    username: admin
  rotateInterval: 4380h
