metadata:
  name: grafana
  path: grafana
  timestamp: '2025-05-10T12:09:28+00:00'
spec:
  enableVersioning: true
  generated:
  - password
  import: false
  public:
    username: admin
  rotateInterval: 4380h
