metadata:
  name: grafana
  path: grafana
  timestamp: '2025-05-06T09:47:41+00:00'
spec:
  enableVersioning: false
  generated:
  - password
  import: false
  public:
    username: admin
  rotateInterval: 4380h
