metadata:
  name: grafana
  # path to the kv secret (excluding the mount path)
  path: grafana
  # timestamp of when the secret was last updated
  timestamp: "2025-05-05T10:18:59+00:00"
spec:
  # key-value map of public (fixed) keys and values (e.g. username, IDs, etc.)
  public:
    username: admin
  # list of secret keys whose values need to be generated and passed in to vault
  generated:
    - password
  # whether this secret should be imported from an existing secret in vault
  import: false
  # interval in which the secret needs to be rotated (regenerated); omit if it shouldn't be rotated automatically
  rotateInterval: 4380h
