metadata:
  name: static-role
spec:
  # role type; can be "static" or "dynamic"
  type: static
  # name of the database user to associate to the role; omit to generate dynamic roles with unique usernames
  # NOTE: the user MUST EXIST in the database
  username: static-role-user
  # the number of seconds between password rotations
  # WARN: CANNOT be used with rotationSchedule or rotationWindow
  rotationPeriodSeconds: 60 # 1 minute
  # the rotation schedule in cron syntax
  # WARN: CANNOT be used with rotationPeriodSeconds
  #rotationSchedule: "0 0 * * 6" # 12AM on Saturdays
  # the number of seconds in which rotations can occur starting from the rotationSchedule
  # WARN: REQUIRE rotationSchedule; CANNOT be used with rotationPeriodSeconds
  #rotationWindowSeconds: 86400 # 1 day
  # list of database statements (in JSON format) to execute during rotations
  #rotationStatements: []
